name: push docker image

on:
  push:
    branches:
      - main
      - rc-*
      - 9c-main
      - development

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: login
        run: docker login --username '${{ secrets.DOCKER_USERNAME }}' --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: cleanup
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: build
        run: docker build . -t planetariumhq/ninechronicles-headless:git-${{ github.sha }} --build-arg COMMIT=git-${{ github.sha }}
      - name: push git-version
        run: docker push planetariumhq/ninechronicles-headless:git-${{ github.sha }}

