name: push docker image

on:
  push:
    branches:
      - main
      - rc-*
      - 9c-main
      - development
      - v100110-say-transport-arm64

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: login
        run: docker login --username '${{ secrets.DOCKER_USERNAME }}' --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: setup-qemu
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: build-and-push-amd64
        run: |
            docker build . -f Dockerfile.amd64 -t planetariumhq/ninechronicles-headless:git-${{ github.sha }}-amd64 --build-arg COMMIT=git-${{ github.sha }}
            docker push planetariumhq/ninechronicles-headless:git-${{ github.sha }}-amd64
      - name: build-and-push-arm64v8
        run: |
            docker build . -f Dockerfile.arm64v8 -t planetariumhq/ninechronicles-headless:git-${{ github.sha }}-arm64v8 --build-arg COMMIT=git-${{ github.sha }}
            docker push planetariumhq/ninechronicles-headless:git-${{ github.sha }}-arm64v8
      - name: merge-manifest-and-push
        run: |
            docker manifest create planetariumhq/ninechronicles-headless:git-${{ github.sha }} --amend planetariumhq/ninechronicles-headless:git-${{ github.sha }}-amd64 --amend planetariumhq/ninechronicles-headless:git-${{ github.sha }}-arm64v8
            docker manifest push planetariumhq/ninechronicles-headless:git-${{ github.sha }}

